import { ArrowLeft, Ban, Repeat2 } from 'lucide-react';
import { CardFace } from './CardView.js';
export const HelpView = ({ onBack }: { onBack: () => void }) => <main className="help-screen">
  <header className="section-heading"><div><p className="eyebrow">THE RULES OF THE TABLE</p><h2>One last card. One big moment.</h2></div><button className="ghost-button" onClick={onBack}><ArrowLeft size={16}/>Back</button></header>
  <section className="help-intro"><div><h3>First to an empty hand wins.</h3><p>Everyone starts with seven cards. Match the discard by color, number, or action symbol. A Wild changes the color. No stacking unless your host enables the house rule.</p><p>Draw one card when you cannot play, or choose to draw. You may play only that newly drawn card or pass. A Draw Two or Draw Four makes the next player draw and lose their turn.</p></div><div className="help-cards"><CardFace card={{ id: 'r', type: 'number', color: 'red', value: 7 }}/><CardFace card={{ id: 'y', type: 'number', color: 'yellow', value: 7 }}/></div></section>
  <div className="help-rule-grid"><article><Ban/><h3>Skip</h3><p>The next player misses their turn.</p></article><article><Repeat2/><h3>Reverse</h3><p>Switch direction. With two players, it acts as Skip.</p></article><article><strong>+2</strong><h3>Draw Two</h3><p>The next player draws two and misses their turn.</p></article><article><strong>+4</strong><h3>Wild Draw Four</h3><p>Choose a color. You can only play it if you have no card of the current color. Illegal +4 plays are blocked automatically; there is no bluff or challenge phase.</p></article></div>
  <section className="help-section"><h3>Don't forget to call UNO.</h3><p>Press UNO before playing from two cards to one, or immediately afterward. An opponent can catch a missed call for a two-card penalty until the next player draws or plays.</p></section>
  <section className="help-section"><h3>A table for your friends.</h3><p>Create a room and share its six-character code or invite link. Friends open the same game address and join. For nearby play, all devices can use the host computer's network address on the same Wi-Fi or hotspot. The host starts the round, adds bots, and starts rematches. Reopening the same browser tab restores a disconnected seat while the server remains running.</p></section>
  <section className="help-section"><h3>House rules</h3><p><b>Stack +2 / +4:</b> pass a draw penalty onward with the same draw type. A stacked +4 is allowed regardless of your other colors. <b>Jump In:</b> play an identical colored card out of turn. Wilds cannot jump in. <b>Seven / Zero:</b> a seven swaps hands with your chosen player; a zero rotates all hands in the current direction. Your last card always ends the round. <b>Force Play:</b> a playable drawn card is played automatically, using your strongest color or smallest opposing hand.</p></section>
  <section className="help-section"><h3>Timers & points</h3><p>When time runs out you draw and pass, or pass if you already drew. Number cards score their value, action cards score 20, and wild cards score 50. The winner earns the total of all remaining hands, including a final draw penalty. New rounds use a number card as the opening discard.</p></section>
</main>;
