import { Music2, RotateCcw, Volume2 } from 'lucide-react';
import { DEFAULT_SETTINGS } from '@uno/shared';
import type { AiDifficulty, GameSettings, ThemeName } from '@uno/shared';

interface Props { settings: GameSettings; onChange: (settings: GameSettings) => void; playerName: string; onRename: (name: string) => void; musicEnabled: boolean; onToggleMusic: () => void }
export const SettingsView = ({ settings, onChange, playerName, onRename, musicEnabled, onToggleMusic }: Props) => {
  const patch = (part: Partial<GameSettings>) => onChange({ ...settings, ...part });
  return <main className="settings-screen"><header className="section-heading"><div><p className="eyebrow">MAKE YOURSELF AT HOME</p><h2>Your game. Your way.</h2></div><button className="ghost-button" onClick={() => onChange({ ...DEFAULT_SETTINGS })}><RotateCcw size={16}/>Reset</button></header>
    <section className="settings-section"><div><h3>Profile & appearance</h3></div><div className="settings-fields"><label className="field">Player name<input value={playerName} maxLength={24} onChange={(event) => onRename(event.target.value)} autoComplete="nickname"/></label><fieldset><legend>Table theme</legend><div className="theme-options">{(['classic', 'midnight', 'neon', 'paper'] as ThemeName[]).map((theme) => <button key={theme} aria-pressed={settings.theme === theme} className={`theme-option ${theme} ${settings.theme === theme ? 'chosen' : ''}`} onClick={() => patch({ theme })}><span/>{theme === 'paper' ? 'Daylight' : theme}</button>)}</div></fieldset></div></section>
    <section className="settings-section"><h3>Sound studio</h3><div className="settings-fields"><label className="field"><span><Volume2 size={17}/> Sound effects <b>{Math.round(settings.soundVolume * 100)}%</b></span><input type="range" min="0" max="1" step=".01" value={settings.soundVolume} onChange={(event) => patch({ soundVolume: Number(event.target.value) })}/></label><label className="field"><span><Music2 size={17}/> Background music <b>{Math.round(settings.musicVolume * 100)}%</b></span><input type="range" min="0" max="1" step=".01" value={settings.musicVolume} onChange={(event) => patch({ musicVolume: Number(event.target.value) })}/></label><button className="ghost-button" onClick={onToggleMusic}><Music2 size={16}/>{musicEnabled ? 'Pause music' : 'Play music'}</button></div></section>
    <section className="settings-section"><h3>At the table</h3><div className="settings-fields"><fieldset><legend>AI difficulty</legend><div className="segmented">{(['easy', 'medium', 'hard'] as AiDifficulty[]).map((aiDifficulty) => <button key={aiDifficulty} aria-pressed={settings.aiDifficulty === aiDifficulty} className={settings.aiDifficulty === aiDifficulty ? 'is-selected' : ''} onClick={() => patch({ aiDifficulty })}>{aiDifficulty}</button>)}</div></fieldset><label className="field">Turn timer<select value={settings.turnTimerSeconds} onChange={(event) => patch({ turnTimerSeconds: Number(event.target.value) })}>{[0, 15, 30, 45, 60, 90, 120].map((seconds) => <option key={seconds} value={seconds}>{seconds ? seconds + ' seconds' : 'No timer'}</option>)}</select></label><div className="toggle-grid">{[['stackDrawTwo', 'Stack Draw Two'], ['stackDrawFour', 'Stack Draw Four'], ['jumpIn', 'Jump In'], ['sevenZero', 'Seven / Zero'], ['forcePlay', 'Force Play']].map(([key, label]) => <label className="toggle" key={key}><span>{label}</span><input type="checkbox" checked={Boolean(settings[key as keyof GameSettings])} onChange={(event) => patch({ [key]: event.target.checked })}/></label>)}</div></div></section>
    <section className="settings-section"><h3>Accessibility</h3><div className="settings-fields">{[['reducedMotion', 'Reduced motion'], ['highContrast', 'High contrast']].map(([key, label]) => <label className="toggle" key={key}><span>{label}</span><input type="checkbox" checked={Boolean(settings[key as keyof GameSettings])} onChange={(event) => patch({ [key]: event.target.checked })}/></label>)}</div></section>
  </main>;
};
